[tool.poetry]
name = "dtsense-rag"
version = "0.1.0"
description = "RAG DTSense using Milvus"
authors = ["Alvin Rindra Fazrie"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
langchain = "^0.3.4"
langchain-groq = "^0.2.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.33"
fastapi = "^0.115.0"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "dtsense_rag"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["Groq"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
